# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f744531bde1c7636e948ba7bcf3d134598a0a27dcbf89db5e49049dcf58112d053c3e150db0cd1a9b3a21e3b4cd5774d449d9644be0b19268693d4f942993f6b

test:
  secret_key_base: 2105d527b1462a275b8c5e4436f10a0cfc3ff7541dcd19f25fc5a94356350a335914559279b6303cb3729a2eccd94d3d7ab87a88998156d84ee24e68e7d53839

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
